### ISSUE TITLE
Enable Travis CI for the repo

### ISSUE THREAD

**Issue by hugovk** [dariusk/wordfilter#18]
Please can you enable Travis CI (and possibly Coveralls) so that PRs will be tested automatically before merge?

Then you'll get reports a bit like:
https://travis-ci.org/hugovk/wordfilter
https://coveralls.io/github/hugovk/wordfilter

Enable them here, both free for open source:
https://travis-ci.org/profile/
https://coveralls.io/repos/new

**Comment by dariusk** [comment]
That's weird, I thought I enabled it... fixing that.

**Comment by dariusk** [comment]
Fixed in 8945dda861f, https://travis-ci.org/dariusk/wordfilter (unit tests failing in Python 3.2)
