### ISSUE TITLE
Errors importing from PyPi on Python 3.6

### ISSUE THREAD

**Issue by jeancochrane** [dariusk/wordfilter#37]
When running an import command on Python 3.6:

```python
from wordfilter import Wordfilter
```

I get the following error message:

```
/path/to/python3.6/site-packages/wordfilter/wordfilter.py in __init__(self, blacklist, datafile)
     27         else:
     28             data = resource_string('wordfilter', '../badwords.json').decode('utf-8')
---> 29             self.blacklist = [s.lower() for s in json.loads(data, 'r')]
     30
     31     def blacklisted(self, string):

TypeError: loads() takes 1 positional argument but 2 were given
```

I was able to successfully import the package by removing the second argument, but then none of the methods except for `blacklisted()` seemed to load:

```python
In [1]: from wordfilter import Wordfilter

In [2]: filt = Wordfilter()

In [3]: filt.blacklisted('bitch')
Out[3]: True

In [4]: filt.removeWord('bitch')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-03c22b14e163> in <module>()
----> 1 filt.removeWord('bitch')

AttributeError: 'Wordfilter' object has no attribute 'removeWord'
```

This may be expected behavior, but I figured I'd file an issue just in case! I'm on OS X, if that helps at all. I was also able to get around this issue by twiddling things on my end, so this is not a high-priority issue.

**Comment by hugovk** [comment]
There are two problems here.

The first is fixable the way you found, and there's already a pending PR: https://github.com/fitnr/wordfilter/pull/2

The second: you may notice the PR is fo a fork of this repo, and that's the installed by pip. And that also renamed the functions in the Python style: so remove_word not removeWord.

It would make sense merge the fork changes back upstream here.

Ping @fitnr

**Comment by jeancochrane** [comment]
That makes sense! Thanks for the clarification @hugovk. I'll close this, since it seems like you all are on top of the issue already.
