### ISSUE TITLE
“goy[im]” is not a term of oppression

### ISSUE THREAD

**Issue by fluffy-critter** [dariusk/wordfilter#47]
It literally just means “non-Jew” and is a term used by Jewish people primarily when discussing cultural issues including oppression of Jewish people.

**Comment by hugovk** [comment]
It doesn't look so clear cut: 

* https://www.jta.org/2019/04/22/culture/is-goy-a-slur
* https://www.ou.org/life/inspiration/jewish-n-word/

And this list isn't a definitive list of "words of oppression", it's words Darius wouldn't say himself, and doesn't want his bots to say. The output of bots can be extremely random, from many different contexts, and placed into many more different contexts, and it can be better to err on the side of caution and just skip some. And it's usually extremely easy and cheap to generate another potential output.

**Comment by fluffy-critter** [comment]
That’s fair. I guess the issue is not wanting the word used inappropriately and out of context by a bot, and the term can be loaded in some contexts.

**Comment by dariusk** [comment]
On consultation with someone who knows the subtleties better than me, I agree with this issue and have removed the terms in d44e719435853c14530c5c7583f6eafc4e71e6b4
